### ISSUE TITLE
Could not execute the method because either the method itself or the containing type is not fully instantiated.

### ISSUE THREAD

**Issue by GVI-Dev3** [pamidur/aspect-injector#51] opened 2016-11-22 12:30 UTC
Hi, i found this issue when working with static method in a Generic function.
This is my class model:
```

  class Program
    {
        static void Main(string[] args)
        {
            SampleClass<int>.Method1(222);
            SampleClass<int>.Method2();

            Console.ReadLine();
      
         
        }
        
    }
  [Aspect(typeof(MyLogging))]
    public class SampleClass<T>
    {
        public static void Method1(int x)
        {
            Console.WriteLine("x");
            //...
        }

        public static int Method2()
        {
            Console.WriteLine("x");

            return 1;
        }
    }
```

**Comment by pamidur** [comment] 2016-11-22 12:43
Thank you for report. Would you mind providing aspect code itself?

**Comment by GVI-Dev3** [comment] 2016-11-22 12:50
Yes, this is my sample code:
https://www.dropbox.com/s/980j7vcg4did3zu/ConsoleApplication2.zip

**Comment by pamidur** [comment] 2016-11-23 11:03
#44 seem to be the same

**Comment by pamidur** [comment] 2016-11-23 11:05
Yes, it is definitely a duplicate of #44

**Closed by pamidur** 2016-11-23 11:05 UTC
Labels: bug
