### ISSUE TITLE
Not throw TaskCanceledException

### ISSUE THREAD

**Issue by om2804** [pamidur/aspect-injector#52] opened 2016-11-29 14:26 UTC
Version 1.0.0-beta4
I'm test this code:
```
    public class StupidAspect
    {
        [Advice(InjectionPoints.Before, InjectionTargets.Method)]
        public void StartMethod([AdviceArgument(AdviceArgumentSource.Name)]string methodName)
        {
            Console.WriteLine("start " + methodName);
        }

        [Advice(InjectionPoints.After, InjectionTargets.Method)]
        public void StopMethood([AdviceArgument(AdviceArgumentSource.Name)]string methodName)
        {
            Console.WriteLine("end " + methodName);
        }        
    }

    [Aspect(typeof(StupidAspect))]
    public class TestClass
    {
        CancellationToken token;
        private CancellationTokenSource cancellationTokenSource;

        public TestClass()
        {
            cancellationTokenSource = new CancellationTokenSource();
            token = cancellationTokenSource.Token;
        }

        public async Task Start()
        {
            await Method1();
        }

        private async Task Method1()
        {
            try
            {
                await Wait(); // must throw exception
            }
            catch (Exception exp)
            {
                Console.WriteLine("Operation cancel");
            }
        }

        private async Task Wait()
        {
            await Task.Delay(10000, token);
        }

        public void Cancel()
        {
            cancellationTokenSource.Cancel();
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            TestClass testClass = new TestClass();
            testClass.Start();
            testClass.Cancel();
            Console.ReadKey();
        }
    }
```

Console output:
```
start Start
start Method1
start Wait
start Cancel
end Cancel
end Wait
end Method1
end Start
```
Must be:
```
start Start
start Method1
start Wait
start Cancel
Operation cancel
end Cancel
end Wait
end Method1
end Start
```

**Comment by pamidur** [comment] 2016-11-29 16:29
Thank you! I'll be fixing it.

The continuations action should process cancellations and exceptions

```c#
Action<Task> continuationAction = delegate(Task task2)
	{
		if (task2.IsCompleted)
		{
			if (!task2.IsFaulted)
			{
				__$a_this_ref.__a$i_StupidAspect.StopMethood("Wait");
				__$a_Wait_tcs.SetResult(null);
			}
		}
		else
		{
			__$a_Wait_tcs.SetResult(null);
		}
	};
```
+ SetException
+ SetCanceled

**Comment by om2804** [comment] 2017-02-23 07:05
>  I'll be fixing it
:(

**Comment by pamidur** [comment] 2017-02-23 08:49
Sorry I've made you wait :(
We had to review all the the codebase due to serious issue with Generics and unpredictable behavior. This issue is fixed now in 'refactoring' branch, though no build yet.
P.s. You will find a lot of breaking changes there, but they are for the best. Check tests for examples.

**Comment by pamidur** [comment] 2017-04-18 12:16
Fixed in https://github.com/pamidur/aspect-injector/releases/tag/1.0.0-rc1

**Closed by pamidur** 2017-04-18 12:16 UTC
Labels: bug

**Comment by om2804** [comment] 2017-04-18 13:23
Yeah! Thx

**Comment by pamidur** [comment] 2017-04-18 13:28
@om2804, could you please test the new release on your specific cases and let us know if it works as intended?
