### ISSUE TITLE
Edit & Continue Support | CS7038

### ISSUE THREAD

**Issue by oleksandrp1** [pamidur/aspect-injector#138] opened 2020-11-12 11:54 UTC
Hi, Thank you for your package. It is very useful, but after adding it to my project I cannot change my code during the debugging session. Each time I receive the following code after a change of at least one symbol:
CS7038	Failed to emit module 'project name': Changing the version of an assembly reference is not allowed during debugging: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' changed version to '2.1.0.0'.
The error disappears when I remove the package.

**Comment by pamidur** [comment] 2020-11-12 11:57
Hi @oleksandrp1 , do you mean "edit and continue feature"?

**Comment by oleksandrp1** [comment] 2020-11-12 12:34
![image](https://user-images.githubusercontent.com/23483761/98940740-1b165280-24f4-11eb-9371-66259181c509.png)
I receive the following message.

**Comment by pamidur** [comment] 2020-11-12 12:41
Thanks for the report, I'll look into it

**Comment by oleksandrp1** [comment] 2020-11-12 12:52
The error disappears if I remove and install the package again. But the error appears after the second launch of the Visual Studio,

**Comment by pamidur** [comment] 2020-11-20 20:04
I've found the cause of the issue, but can't figure how to fix it at the moment :(

**Comment by oleksandrp1** [comment] 2021-03-23 20:29
Hi pamidur. After update to 2.5.0 version, the following warning message appears during debugging. The problem disappears if I remove the package.
![image](https://user-images.githubusercontent.com/23483761/112213794-1fcbdf80-8c27-11eb-8868-dceb41e47afb.png)

**Comment by pamidur** [comment] 2021-03-23 20:53
hi @oleksandrp1 , do you use 'Edit&Continue' feature ? and if no, could you provide a bit more information. maybe sample code?

**Comment by oleksandrp1** [comment] 2021-03-23 21:07
Yes, I use 'Edit&Continue' feature.

**Comment by pamidur** [comment] 2021-03-23 21:12
The weird part that is should also fail in 2.4.3 then! And you're saying it doesn't. Very interesting!
Is there any chance you could provide code sample and/or steps to reproduce?

**Comment by oleksandrp1** [comment] 2021-03-23 21:16
Excuse me. I mixed 2 problems in one issue. The error with the "Edit" and "Stop" buttons appears in 2.4.3, 2.4.4, and 2.5.0 versions.
The error about breakpoints appears in 2.4.4 and 2.5.0. It does not appear in 2.4.3.

**Comment by pamidur** [comment] 2021-03-23 21:21
In 2.4.4 I changed (fixed) the way debug data is handled. It seems like something isn't working as expected.
Could you please create another issue and provide steps to reproduce and code sample (the method where you try to set breakpoint) if possible?

**Comment by oleksandrp1** [comment] 2021-03-30 10:38
[Example.zip](https://github.com/pamidur/aspect-injector/files/6228339/Example.zip)
This is an attachment for this problem, but the bug about the breakpoint is not reproduced here. It is a simplified version of my project, but now I did not find what causes the breakpoint problem. I will investigate it later.

**Comment by pamidur** [comment] 2021-03-30 10:43
Thanks for your report! The sample code will help a lot!

**Comment by oleksandrp1** [comment] 2021-03-30 10:54
The problem with the breakpoints is not reproduced now at all. Maybe cleaning the project and update of other packages solved the problem.

**Comment by pamidur** [comment] 2021-03-30 10:56
well, it potentially could be a weird extension of Edit&Continue bug

**Comment by marbel82** [comment] 2021-08-10 13:09
A similar problem: https://github.com/AvaloniaUI/Avalonia/issues/5456

**Comment by pamidur** [comment] 2021-08-10 13:16
Hi @marbel82 , have tried 2.6.0-pre1 version?

**Comment by oleksandrp1** [comment] 2021-08-11 09:42
In 2.6.0-pre1 it is possible to debug the code and to go to highest rows in the code, but after changing the code it shows the message
![image](https://user-images.githubusercontent.com/23483761/129007228-9f248aa2-63d0-4416-8493-fad2ca5930ca.png)

**Comment by pamidur** [comment] 2021-08-11 09:48
@oleksandrp1 , could you please provide a code-sample (or project-sample) so we can reproduce it?

**Comment by oleksandrp1** [comment] 2021-08-30 07:29
[Example.zip](https://github.com/pamidur/aspect-injector/files/7074983/Example.zip)
Hi, now the message does not appear, but I found that if I add changes to the code during debugging then they will not be applied to the code during the debugging. Open WebRefactorPage.cs and make a breakpoint on string 23 and on string 25. Run debugging a test in TS09General.cs file. If you change the "a" variable to "true" on string 23 then it will not be applied to the debugging mode and the step 25 will apply the previous "false" value.

**Comment by oleksandrp1** [comment] 2021-08-31 15:11
Thank you for your product!

**Comment by JunkyXL86** [comment] 2021-09-08 08:01
I've got the same error trying to change code in a Xamarin.Forms 5.0.0.2012 App using Edit & Continue with Visual Studio 2022 Preview 3.1:
`CS7038	Failed to emit module 'XF.App': Changing the version of an assembly reference is not allowed during debugging: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' changed version to '2.1.0.0'.`

**Comment by marbel82** [comment] 2021-09-10 07:31
I found the cause in my case. In all projects I have set TargetFramework to `net5.0-windows`, but in one I had set `net.5.0`. When I changed in this latest project to `net5.0-windows`, the problem with inability to edit disappeared.

**Comment by pamidur** [comment] 2021-10-18 14:04
oh, I got it, it does mean that issue could be somewhere else, thanks @marbel82

**Comment by pamidur** [comment] 2022-01-21 22:09
Seems fixed in 2.7.0

**Closed by pamidur** 2022-01-21 22:09 UTC
Labels: bug, enhancement, investigation
