### ISSUE TITLE
Can i use in assembly level?

### ISSUE THREAD

**Issue by drony** [pamidur/aspect-injector#83] opened 2019-02-07 13:10 UTC
when i tried i got this error

### aspect file
    [Aspect(Scope.Global)]
    [Injection(typeof(LoggingAspect))]
    [AttributeUsage(AttributeTargets.All, Inherited = false)]
    public class LoggingAspect : Attribute

### in assembly
[assembly: LoggingAspect()]

```
4>C:\Users\xxxx\source\Workspaces\xxx\xxx\Abstract\Device.cs(14,21,14,23): warning CS0169: The field 'Device.v2' is never used
4>  AspectInjector: Started for TPS.Hardware.dll
4>  AspectInjector: Assembly has been read.
4>  AspectInjector: Found 0 aspects
4>  AspectInjector: Found 1218 injections
4>  AspectInjector: Processing injections...
4>  AspectInjector: Executing AdviceInlineWeaver...
4>  AspectInjector: Executing AdviceStateMachineWeaver...
4>  AspectInjector: Executing AdviceAroundWeaver...
4>AspectInjector : error AI_ERR0: Processing failure: System.NullReferenceException: Object reference not set to an instance of an object.
4>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceAroundProcess.MoveBody(MethodDefinition from, MethodDefinition to)
4>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceAroundProcess.WrapEntryPoint(MethodDefinition unwrapper)
4>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceAroundProcess.GetOrCreateUnwrapper()
4>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceAroundProcess.GetNextWrapper()
4>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceAroundProcess.Execute()
4>     at AspectInjector.Core.Processor.ProcessAssembly(AssemblyDefinition assembly, Boolean optimize)
4>     at AspectInjector.Core.Processor.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize)
4>     at AspectInjector.Commands.ProcessCommand.Execute(IReadOnlyList`1 args). Please submit an issue to https://github.com/pamidur/aspect-injector
4>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors.
5>------ Build started: Project:xxxxx.Test.App, Configuration: Debug x86 ------
```

**Comment by pamidur** [comment] 2019-02-07 13:23
Hi,
I could not reproduce this case. I suspect aspectInjector tries to wrap around method which is not a method somehow (idk, maybe something from COM or p/invoke). 
Could you please provide more code so we can see what exactly in the Assembly you're injecting to?

**Comment by pamidur** [comment] 2019-02-07 13:50
Ok, i found a problem. This is regression issue with abstract and external methods which was already fixed before. I'll fix it soon

**Comment by pamidur** [comment] 2019-02-07 14:11
fixed in 2.0.3

**Closed by pamidur** 2019-02-07 14:11 UTC
Labels: bug

**Comment by drony** [comment] 2019-02-07 14:14
I've just updated. but i thin there is a problem with static Main function

 public object HandleMethod(
            [Argument(Source.Instance)] object **instance**,
            [Argument(Source.Name)] string name,
            [Argument(Source.Arguments)] object[] arguments,
            [Argument(Source.Target)] Func<object[], object> method)
        {

instance is null and i handle instance this time application exit immediately

**Comment by pamidur** [comment] 2019-02-07 14:18
This is by design. 
Static methods (like Main() ) don't have _this_ and you'll receive [Argument(Source.Instance)] object **instance** = null.

You have to check if instance is null and the process it correctly. Btw you can use [Argument(Source.Type)] this is always not-null

**Comment by drony** [comment] 2019-02-07 14:22
thanks but this is a new errors

6>  AspectInjector: Started forxxx.dll
6>  AspectInjector: Assembly has been read.
6>  AspectInjector: Found 0 aspects
6>  AspectInjector: Found 958 injections
6>  AspectInjector: Processing injections...
6>  AspectInjector: Executing AdviceInlineWeaver...
6>  AspectInjector: Executing AdviceStateMachineWeaver...
6>  AspectInjector: Executing AdviceAroundWeaver...
6>AspectInjector : error AI_ERR0: Processing failure: System.NotSupportedException: Specified method is not supported.
6>     at AspectInjector.Core.Models.PointCut.PickLoadInstruction(TypeReference elemType)
6>     at AspectInjector.Core.Models.PointCut.Cast(TypeReference typeOnStack, TypeReference expectedType)
6>     at AspectInjector.Core.Fluent.Arrays.SetByIndex(PointCut pc, TypeReference elementType, Int32 index, Action`1 value)
6>     at AspectInjector.Core.Fluent.Arrays.CreateArray(PointCut pc, TypeReference elementType, Action`1[] elements)
6>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceWeaveProcessBase`1.LoadArgumentsArgument(PointCut pc, AdviceArgument parameter)
6>     at AspectInjector.Core.Models.PointCut.Store(VariableDefinition variable, Action`1 val)
6>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceAroundProcess.<>c__DisplayClass11_0.<WrapEntryPoint>b__0(PointCut e)
6>     at AspectInjector.Core.Fluent.MethodEditor.Instead(Action`1 action)
6>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceAroundProcess.WrapEntryPoint(MethodDefinition unwrapper)
6>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceAroundProcess.GetOrCreateUnwrapper()
6>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceAroundProcess.GetNextWrapper()
6>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceAroundProcess.Execute()
6>     at AspectInjector.Core.Processor.ProcessAssembly(AssemblyDefinition assembly, Boolean optimize)
6>     at AspectInjector.Core.Processor.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize)
6>     at AspectInjector.Commands.ProcessCommand.Execute(IReadOnlyList`1 args). Please submit an issue to https://github.com/pamidur/aspect-injector
6>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors.
7>------ Build started: Project:xxx, Configuration: Debug Any CPU ------
7>  All packages listed in packages.config are already installed.

**Comment by pamidur** [comment] 2019-02-07 14:32
Do you use unsafe code? 
It seems there is some unusual method argument is your code.

**Comment by drony** [comment] 2019-02-07 14:40
yes unsafe code available

**Comment by pamidur** [comment] 2019-02-07 14:43
Can I have any sample on there you pass pointers into method as a parameters?

**Comment by drony** [comment] 2019-02-07 14:57
actually this is a very very large library. i prepare lightweight sample soon as possible.
thanks for your help

**Comment by drony** [comment] 2019-02-07 15:33
I've recompiled this line from source code:

AspectInjector.Core>Fluent>PointCut.cs

private Instruction PickStoreInstruction(TypeReference parameterType)
        {
            var elemType = ((ByReferenceType)parameterType).ElementType;

            switch (elemType.MetadataType)
            {
                case MetadataType.Class: return CreateInstruction(OpCodes.Stind_Ref);
                case MetadataType.Object: return CreateInstruction(OpCodes.Stind_Ref);
                case MetadataType.MVar: return CreateInstruction(OpCodes.Stobj, elemType);
                case MetadataType.Var: return CreateInstruction(OpCodes.Stobj, elemType);
                case MetadataType.Double: return CreateInstruction(OpCodes.Stind_R8);
                case MetadataType.Single: return CreateInstruction(OpCodes.Stind_R4);
                case MetadataType.Int64: return CreateInstruction(OpCodes.Stind_I8);
                case MetadataType.UInt64: return CreateInstruction(OpCodes.Stind_I8);
                case MetadataType.Int32: return CreateInstruction(OpCodes.Stind_I4);
                case MetadataType.UInt32: return CreateInstruction(OpCodes.Stind_I4);
                case MetadataType.Int16: return CreateInstruction(OpCodes.Stind_I2);
                case MetadataType.UInt16: return CreateInstruction(OpCodes.Stind_I2);
                case MetadataType.Byte: return CreateInstruction(OpCodes.Stind_I1);
                case MetadataType.SByte: return CreateInstruction(OpCodes.Stind_I1);
                case MetadataType.Boolean: return CreateInstruction(OpCodes.Stind_I1);
                case MetadataType.Char: return CreateInstruction(OpCodes.Stind_I2);
                case MetadataType.UIntPtr: return CreateInstruction(OpCodes.Stind_I);
                case MetadataType.IntPtr: return CreateInstruction(OpCodes.Stind_I);
                case MetadataType.String: return CreateInstruction(OpCodes.Stind_I);
            }

            **throw new NotSupportedException(elemType.MetadataType.ToString());**
        }


**here is the missing type:** -> **String**

5>  All packages listed in packages.config are already installed.
5>  AspectInjector: Started for xxx.dll
5>  AspectInjector: Assembly has been read.
5>  AspectInjector: Found 0 aspects
5>  AspectInjector: Found 42 injections
5>  AspectInjector: Processing injections...
5>  AspectInjector: Executing AdviceInlineWeaver...
5>  AspectInjector: Executing AdviceStateMachineWeaver...
5>  AspectInjector: Executing AdviceAroundWeaver...
5>AspectInjector : error AI_ERR0: Processing failure: System.NotSupportedException: **String**

**Comment by drony** [comment] 2019-02-07 15:35
and it think add this line should be fix:

 **case MetadataType.String: return CreateInstruction(OpCodes.Ldind_Ref);**

**Comment by drony** [comment] 2019-02-07 16:04
for my project:

MetadataType.ValueType
MetadataType.GenericInstance
MetadataType.String
MetadataType.Array


missing in pointcut.cs in two location

**Comment by pamidur** [comment] 2019-02-07 16:29
have a try 2.0.5

**Comment by drony** [comment] 2019-02-08 13:51
thanks it works
