### ISSUE TITLE
Full Framework gets reference to CoreLib

### ISSUE THREAD

**Issue by MrVerifit** [pamidur/aspect-injector#70] opened 2018-06-20 07:57 UTC
Can you please make it usable with .net40?

**Comment by pamidur** [comment] 2018-06-20 12:58
That's going to be challenging. The limitation is the lowest framework's version that supports asycn/await. However it might work on even lower version, I'll give it a shot...

**Comment by MrVerifit** [comment] 2018-06-21 05:35
[https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if](url) this link can help you

**Comment by pamidur** [comment] 2018-06-29 06:47
It's a bit more complicated than that:
The actual injector is framework version agnostic. Even more the next version of injector is going to be built on net core 2.1. This means that you'll need installed netcore21 on your machine. However your target code might as low as net45.
Now why net45?
Although the injector is version agnostic there is a bridge between your code and injector that is AspectInjector.Broker.dll and is should be supported by both your code and injector. So we use netstandard1.0 for Broker as it is lowest version supported by netcore. And netstandard1.0 might be referenced by net45 assemblies (I think it has something to do with async/await).

So **tldr;** We basically support all framework versions that support netstandard1.0
see chart here https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by mmoroni** [comment] 2019-04-28 21:07
Hello there. I’m thrilled with this package, but I was unable to make it work using the full .net framework.
Is there any plans on making it .net standard 2.0 compatible? Or am I doing something wrong?
Thx

**Comment by pamidur** [comment] 2019-04-29 06:28
Hi,
It is netstandard2.0 compatible. However the lowest full framework version that supports netstandard2.0 is net461.
If your project is >= net461, you should be able to simply get the package from Nuget. And it should just work. If doesn't, please send your *.csproj file and logs.

**Comment by mmoroni** [comment] 2019-04-29 16:32
Yes, it's net472.
This is the error being thrown: Could not load file or assembly **'System.Private.CoreLib**.

I have attached a full project sample and the full exception below:

[AOPConsole.zip](https://github.com/pamidur/aspect-injector/files/3128280/AOPConsole.zip)
[Error.txt](https://github.com/pamidur/aspect-injector/files/3128284/Error.txt)

Thx, pamidur!

**Comment by pamidur** [comment] 2019-04-29 16:53
Thanks for the report. It looks like regression, because it was already fixed couple of versions ago.

**Comment by pamidur** [comment] 2019-04-29 16:55
Meanwhile you can try prev version

**Comment by pamidur** [comment] 2019-05-03 11:37
Fixed in 2.1.1. Please check and reopen if needed

**Closed by pamidur** 2019-05-03 11:37 UTC
Labels: bug
