### ISSUE TITLE
Docker build/ dotnet build in linux: AspectInjector not found

### ISSUE THREAD

**Issue by izydorkowalsky** [pamidur/aspect-injector#188] opened 2022-07-18 14:45 UTC
**Environment (please complete the following information):**
 - OS: linux
 - Framework: net6.0
 - Type of application: console
 - Version of AspectInjector: 2.7.3
 
AspectInjector is installed viaNuget in V2.7.3 in an net6.0 application. Build-image is alpine6.0-SDK

in dockerfile the Command: RUN dotnet build ... Build fails (also when trying dotnet build in interactive shell in the container) with: 

 /bin/sh: /tmp/tmp5ccf1eb3d33a44c3a5d6afee850a621b.exec.cmd: line 2: /root/.nuget/packages/aspectinjector/2.7.3/buildTransitive/netstandard2.0/../../build/_bin/linux-x64/AspectInjector: not found
AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors. [/src/geronto.services.assessments/geronto.services.assessments.csproj]

In NugetPackage AspectInjector.targets:

    <AspectInjector_Location Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(MSBuildThisFileDirectory)../../build/_bin/linux-x64/AspectInjector</AspectInjector_Location>

Solving the path seems to fail in dotnet build

**Comment by pamidur** [comment] 2022-07-18 15:08
Hi @izydorkowalsky, thanks for the report , let me take a look at it

**Comment by pamidur** [comment] 2022-07-18 15:54
the issue is only with alpine images, I should be able to fix it but meanwhile you can use any other image not based on musl libc (read: ubuntu)

**Comment by izydorkowalsky** [comment] 2022-07-19 07:57
Thank you @pamidur. I'll give it a try on ubuntu  😊

**Comment by pamidur** [comment] 2022-07-21 09:51
Hi @izydorkowalsky , could you please try 2.7.4-pre1?. It has experimental support for musl (alpine) and on my side it works well

**Comment by izydorkowalsky** [comment] 2022-07-21 11:30
@pamidur Works like a charm 👍

**Comment by pamidur** [comment] 2022-07-21 11:31
Great, I'll test a bit more and make a release build in couple of days

**Comment by pamidur** [comment] 2022-07-22 18:38
fixed in 2.7.4

**Closed by pamidur** 2022-07-22 18:38 UTC
Labels: bug
