### ISSUE TITLE
StackOverflowException when applying injection on assembly and running Nunit test

### ISSUE THREAD

**Issue by ocherniavskyi** [pamidur/aspect-injector#80] opened 2019-01-03 00:24 UTC
Visual Studio 2017 Pro 15.9.1

Failed to run nunit tests due to StackOverflowException when applying injection to whole assembly. But it successfully runs when injection applies to class.

[AspectIssue.zip](https://github.com/pamidur/aspect-injector/files/2722417/AspectIssue.zip)

**Comment by pamidur** [comment] 2019-01-03 08:05
Thanks, the issue is there. We still injecting aspects into aspects. This seem like regression. Will be fixed soon

**Closed** 2019-01-03 11:08 UTC
Labels: bug

**Comment by pamidur** [comment] 2019-01-03 11:40
fixed in 2.0.1
