### ISSUE TITLE
Issue passing ref and out params with AdviceArgumentSource.TargetArguments

### ISSUE THREAD

**Issue by pairbit** [pamidur/aspect-injector#27] opened 2016-01-27 13:32 UTC
![Warning](https://cloud.githubusercontent.com/assets/1288091/12614836/5083e61c-c513-11e5-939c-32a203a0fa01.png)

![Result](https://cloud.githubusercontent.com/assets/1288091/12614809/338071f2-c513-11e5-9e48-b34a34158ea5.png)

![Wrong](https://cloud.githubusercontent.com/assets/1288091/12614860/6a4ab742-c513-11e5-9261-53104923812b.png)

![Resolve](https://cloud.githubusercontent.com/assets/1288091/12614806/2c4eb628-c513-11e5-8e87-098f75f0ab42.png)

**Comment by pamidur** [comment] 2016-01-28 11:15
It is expected behavior. This way you can examine out params for instance. Does it confuse? What do you think?

**Comment by Pzixel** [comment] 2016-01-28 11:26
I agree that this behaviour is expected. If variables was changed within a method, when I trace variables before exit I expect that I will actual values, not values that was passed in it.

**Comment by pairbit** [comment] 2016-01-28 12:13
I agree with you, but the ref and out parameters, now is not working.

![2016-01-28_1458](https://cloud.githubusercontent.com/assets/1288091/12644099/89a9b426-c5d1-11e5-9afc-11f268c2641e.png)
![2016-01-28_1501](https://cloud.githubusercontent.com/assets/1288091/12644101/8de1a63e-c5d1-11e5-94b7-89edc4454611.png)

**Comment by pamidur** [comment] 2016-01-28 12:32
Ok, now it looks like a bug.

**Comment by pamidur** [comment] 2016-07-05 12:37
fixed in beta2

**Closed by pamidur** 2016-07-05 12:37 UTC
Labels: bug
